name: Bug report
description: Report a problem in existing functionality, including documentation and infrastructure.
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: input
    id: device
    attributes:
      label: Device
      description: The model of device you're using Dasharo on.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Firmware or software name and version
      description: The name and version of firmware or software you're using (e.g., `Dasharo v0.2.0`), or commit hashes if built from an untagged revision
    validations:
      required: true

  - type: textarea
    id: component
    attributes:
      label: Affected component(s) or functionality
      description: The component or functionality that is not working as expected.
    validations:
      required: false

  - type: input
    id: summary
    attributes:
      label: Brief summary
      description: A clear and concise summary of the bug.
    validations:
      required: true

  - type: textarea
    id: reproductibility
    attributes:
      label: How reproducible
      description: At what rate does the bug occur when the steps to reproduce are performed?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: List of steps to reproduce the behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened instead of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: textarea
    id: solutions
    attributes:
      label: Solutions you've tried
      description: If applicable, any solutions or workarounds you've already tried.
    validations:
      required: false
