name: Bug report
description: Report a problem in existing functionality, including documentation and infrastructure.
labels: ["bug", "needs review"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Please chose components related to this issue.
      multiple: true
      # When updating list of components please also update labeling policy
      # policy: `.github/advanced-issue-labeler.yml`
      options:
        - 'Dasharo firmware'
        - 'Dasharo Tools Suite'
        - 'Dasharo documentation'
        - 'EC firmware'
        - 'other'
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Model of device(s) on which issue was seen on
      multiple: true
      # When updating list of components please also update labeling policy
      # policy: `.github/advanced-issue-labeler.yml`
      options:
        - 'Asus KGPE-D16'
        - 'Dell OptiPlex 7010'
        - 'Dell OptiPlex 9010'
        - 'MSI Pro Z690-A'
        - 'MSI Pro Z790-P'
        - 'NovaCustom NV4x 11th Gen'
        - 'NovaCustom NV4x 12th Gen'
        - 'NovaCustom NS5x 11th Gen'
        - 'NovaCustom NS5x 12th Gen'
        - 'NovaCustom NS7x 11th Gen'
        - 'NovaCustom NS7x 12th Gen'
        - 'NovaCustom V54 14th Gen'
        - 'NovaCustom V56 14th Gen'
        - 'PC Engines APU2'
        - 'PC Engines APU3'
        - 'PC Engines APU4'
        - 'PC Engines APU6'
        - 'Protectli FW2B'
        - 'Protectli FW4B'
        - 'Protectli FW4C'
        - 'Protectli FW6'
        - 'Protectli VP2410'
        - 'Protectli VP2420'
        - 'Protectli VP3210'
        - 'Protectli VP3230'
        - 'Protectli VP4630'
        - 'Protectli VP4650'
        - 'Protectli VP4670'
        - 'Protectli VP6630'
        - 'Protectli VP6650'
        - 'Protectli VP6670'
        - 'QEMU Q35 Emulator'
        - 'Raptor CS Talos II'
        - 'other'
    validations:
      required: true

  - type: input
    id: version-fw
    attributes:
      label: Dasharo version
      description: The version of Dasharo firmware (e.g., `v0.2.0`), or commit hashes if built from an untagged revision; skip if Dasharo firmware has not been used
    validations:
      required: false

  - type: input
    id: version-dts
    attributes:
      label: Dasharo Tools Suite version
      description: The version of Dasharo Tools Suite (e.g., `v1.2.0`), or commit hashes if built from an untagged revision; skip if Dasharo Tool Suite has not been used
    validations:
      required: false

  - type: input
    id: test-case-id
    attributes:
      label: Test case ID
      description: ID of a test which failed and triggered this bug report. Required to be filled in by Dasharo team members, if such test exists.
    validations:
      required: false

  - type: input
    id: summary
    attributes:
      label: Brief summary
      description: A clear and concise summary of the bug.
    validations:
      required: true

  - type: textarea
    id: reproductibility
    attributes:
      label: How reproducible
      description: At what rate does the bug occur when the steps to reproduce are performed?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: List of steps to reproduce the behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened instead of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. You can elaborate here if any of the selections from the list did not match.
    validations:
      required: false

  - type: textarea
    id: solutions
    attributes:
      label: Solutions you've tried
      description: If applicable, any solutions or workarounds you've already tried.
    validations:
      required: false
